---
- name: Setup  Owner internet gateway
  ec2_vpc_igw:
    region: "{{ region }}"
    vpc_id: "{{ owner_vpc_id }}"
  register: owner_igw

- name: Setup Accept internet gateway
  ec2_vpc_igw:
    region: "{{ region }}"
    vpc_id: "{{ acc_vpc_id }}"
  register: acc_igw

- name: Owner VPC Public Router Table 
  ec2_vpc_route_table:
    tags:
      "Name": "{{ owner_vpc_name }}-public"
    region: "{{ region }}"
    vpc_id: "{{ owner_vpc_id }}"
    purge_routes: false
    routes:
      - dest: "{{ acc_cidr_block }}"
        gateway_id: "{{ owner_igw.gateway_id }}"

- name: Accept VPC Public Route Table
  ec2_vpc_route_table:
    vpc_id: "{{ acc_vpc_id }}"
    purge_routes: false
    subnets: "{{ subnet_ec2_ids }}"
    tags:
      Name: "{{ connection_name }}-peering"
    routes:
      - dest: "{{ owner_cidr_block }}"
        gateway_id: "{{ acc_igw.gateway_id }}"
    region: "{{ region }}"

- name: Accept VPC Public Route Table
  ec2_vpc_route_table:
    vpc_id: "{{ acc_vpc_id }}"
    purge_routes: false
    subnets: "{{ subnet_rds_ids }}"
    tags:
      Name: "{{ connection_name }}-peering"
    routes:
      - dest: "{{ owner_cidr_block }}"
        gateway_id: "{{ acc_igw.gateway_id }}"
    region: "{{ region }}"

- name: "{{ connection_name }} All Route Table" 
  ec2_vpc_route_table:
    region: "{{ region }}"
    vpc_id: "{{ acc_vpc_id }}"
    purge_routes: false
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ acc_igw.gateway_id }}"
    tags:
      Name: "{{ connection_name }}-peering"

