---
# tasks file for roles/securitygroups
- name: provision elb  80 and 443 all security group
  ec2_group:
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    name: "{{ vpc_env }}-elb-80-443-all"
    description: "opens port 80 443 to the world"
    tags:
      "Name": "{{ vpc_env }}-elb-80-443-all"
      "Environment": "{{ vpc_env }}-elb-80-443-all"
    rules:
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "0.0.0.0/0"
        rule_desc: "allow all on port 80"
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        cidr_ip: "0.0.0.0/0"
        rule_desc: "allow all on port 443"
  register: sg_elb_80_443_all

