---
# defaults file for roles/subnets

the_subnets:
  - { use: 'ec2', az: 'a', subnet: '10.20.10.0/24' }
  - { use: 'ec2', az: 'b', subnet: '10.20.11.0/24' }
  - { use: 'ec2', az: 'c', subnet: '10.20.12.0/24' }
  
  

