---
# defaults file for roles/subnets

the_subnets:
  - { use: 'ec2', az: 'a', subnet: '10.120.10.0/24' }
  - { use: 'ec2', az: 'b', subnet: '10.120.11.0/24' }
  - { use: 'ec2', az: 'c', subnet: '10.120.12.0/24' }
  - { use: 'rds', az: 'b', subnet: '10.120.30.0/24' }
  - { use: 'rds', az: 'c', subnet: '10.120.31.0/24' }
  - { use: 'rds', az: 'a', subnet: '10.120.32.0/24' }
  
  

