
- name: Get only running instance IP addresses.
  set_fact:
    private_ips: "{{ ec2_zuul.tagged_instances|map(attribute='private_ip')|list }}"

- name: Configure hostname in /home/centos/new-project/aws-project/002.os-sys-docker/inventory/hosts
  lineinfile:
    state: present
    dest: /home/centos/new-project/aws-project/002.os-sys-docker/inventory/hosts
    regexp: "{{ ec2_instance_tag_name }}"
    line: "[{{ ec2_instance_tag_name }}]{{'\n'}}{{ private_ips[0] }} ansible_ssh_user={{ ssh_user }} ansible_ssh_private_key_file=/home/centos/.keys/{{ ec2_key_Pair }}"

