---
- name: Create IT Monitor EC2 vHost
  hosts: localhost
  connection: local
  serial: 1
  max_fail_percentage: 0

  vars:
    vpc_env: "M20"
    vpc_region: "ap-east-1"


  roles:
    - role: ec2_drop
