---
# tasks file for roles/securitygroups
- name: provision merchant  8081 all security group
  ec2_group:
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    name: "{{ vpc_env }}-merchant-8081"
    description: "opens port 8081 to the world"
    tags:
      "Name": "{{ vpc_env }}-merchant-8081"
      "Environment": "{{ vpc_env }}-merchant-8081"
    rules:
      - proto: "tcp"
        from_port: "8081"
        to_port: "8081"
        cidr_ip: "154.197.29.34/32"
        rule_desc: "allow all on port 8081"
  register: sg_merchant_8081
