---
- name: Create ElastiCache Redis instance
  hosts: localhost
  connection: local
  gather_facts: True
  serial: 1
  max_fail_percentage: 0

  vars:
    vpc_name: "M120"
    region: "ap-southeast-1"  
    redis_engine_version: "5.0.0"  
    redis_parameter_version: "redis5.0" 
    redis_global_name: 'm120-redis' 

  roles:
    - { role: rds.redis-base }         #创建基础环境
    - { role: rds.redis,redis_cluster_type: cache.r5.large,replicas_nodes: "1",redis_num_nodes: "1",redis_port: "6379",redis_name: "m120-redis5-base" }  #创建Redis Replication Cluster
    - { role: rds.redis,redis_cluster_type: cache.r5.large,replicas_nodes: "1",redis_num_nodes: "1",redis_port: "6379",redis_name: "m120-redis5-session" }  #创建Redis Replication Cluster

