---
# tasks file for roles/securitygroups
- name: provision backend  7880 and 7881 and 7882 all security group
  ec2_group:
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    name: "{{ vpc_env }}-backend-acl"
    description: "opens port 7880 7881 7882 to the world"
    tags:
      "Name": "{{ vpc_env }}-backend-acl"
      "Environment": "{{ vpc_env }}-backend-acl"
    rules:
      - proto: "tcp"
        from_port: "7880"
        to_port: "7880"
        cidr_ip: "0.0.0.0/0"
        rule_desc: "allow all on port 7880"
      - proto: "tcp"
        from_port: "7881"
        to_port: "7881"
        cidr_ip: "0.0.0.0/0"
        rule_desc: "allow all on port 7881"
      - proto: "tcp"
        from_port: "7882"
        to_port: "7882"
        cidr_ip: "0.0.0.0/0"
        rule_desc: "allow all on port 7882"
  register: sg_backend_acl
