---
- name: zuul capture instance facts
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:env": "{{ zuul_env }}"
      instance-state-name: [ "running" ]
      vpc-id: "{{ elb_vpc_id }}"
  register: zuul_instance_facts

- name: "set facts: instance IDs"
  set_fact:
    zuul_instance_ids: '{{ zuul_instance_facts.instances|map(attribute="instance_id")|list }}'

- name: Get appgw SG ID
  ec2_group_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ elb_vpc_id }}"
      group-name: "{{ elb_vpc_name }}-{{ app_appgw_group }}"
  register: sg_appgw

- name: list of appgw all the security group id.
  set_fact:
    sg_appgw_id: "{{ item.group_id }}"
  with_items: "{{ sg_appgw.security_groups }}"

- name: create targets
  set_fact:
    targets: "{{ targets|default([]) + [ {'Id': item, 'Port': 8800 } ] }}"
  with_items: "{{ zuul_instance_ids }}"

- name: Create appgw target group
  elb_target_group:
    name: "{{ elb_vpc_name }}-{{ app_elb_name }}"
    region: "{{ region }}"
    state: "{{ elb_resource_state }}"
    tags:
      env: "{{ elb_vpc_name }}-{{ app_target_name }}"
    protocol: http
    port: 80
    vpc_id: "{{ elb_vpc_id }}"
    health_check_path: "/actuator/info"
    successful_response_codes: "200"
    target_type: instance
    targets: "{{ targets }}"
  register: appgw_tg

- name: Create an ELB Application Load Balancer and attach appgw listener
  elb_application_lb:
    name: "{{ elb_vpc_name }}-{{ app_elb_name }}"
    region: "{{ region }}"
    security_groups:
      - "{{ sg_appgw_id }}" 
    subnets:
      - "{{ subnet_ec2_ids[0] }}" 
      - "{{ subnet_ec2_ids[1] }}" 
      - "{{ subnet_ec2_ids[2] }}" 
    idle_timeout: 600  #seconds
    tags:
      env: "{{ elb_vpc_name }}-{{ app_elb_name }}"
    deletion_protection: true
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: "{{ appgw_tg.target_group_name }}"
        Rules:
          - Conditions:
              - Field: path-pattern
                Values:
                  - '/actuator/info'
            Priority: '1'
            Actions:
              - Type: forward
                TargetGroupName: "{{ appgw_tg.target_group_name }}"
    state: "{{ elb_resource_state }}"
