---
- name: Create a peer-to-peer connection between VPCs 
  hosts: localhost
  connection: local
  gather_facts: True

  vars:
    connection_name: "M120"
    vpc_name: "M120"

    owner_vpc_name: "banna"
    acc_vpc_name: "M120"
    profile: "606724181858"
    region: "ap-southeast-1"

  roles:
    - roles/vpc_peering

  
