---
- name: Get operation SG ID
  ec2_group_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ elb_vpc_id }}"
      group-name: "{{ elb_vpc_name }}-{{ app_office_group }}"
  register: sg_operation

- name: list of operation all the security group id.
  set_fact:
    sg_operation_id: "{{ item.group_id }}"
  with_items: "{{ sg_operation.security_groups }}"

- name: create targets
  set_fact:
    targets: "{{ targets|default([]) + [ {'Id': item, 'Port': 8125 } ] }}"
  with_items: "{{ operation_instance_ids }}"

- name: Create operation target group
  elb_target_group:
    name: "{{ elb_vpc_name }}-{{ app_elb_name }}"
    region: "{{ region }}"
    state: "{{ elb_resource_state }}"
    tags:
      env: "{{ elb_vpc_name }}-{{ app_target_name }}"
    protocol: http
    port: 80
    vpc_id: "{{ elb_vpc_id }}"
    health_check_path: /
    successful_response_codes: "200"
    target_type: instance
    targets: "{{ targets }}"
  register: operation_tg

- name: Create an ELB Application Load Balancer and attach operation listener
  elb_application_lb:
    name: "{{ elb_vpc_name }}-{{ app_elb_name }}"
    region: "{{ region }}"
    security_groups:
      - "{{ sg_operation_id }}" 
    subnets:
      - "{{ subnet_ec2_ids[0] }}" 
      - "{{ subnet_ec2_ids[1] }}" 
      - "{{ subnet_ec2_ids[2] }}" 
    idle_timeout: 600  #seconds
    tags:
      env: "{{ elb_vpc_name }}-{{ app_elb_name }}"
    deletion_protection: true
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: "{{ operation_tg.target_group_name }}"
        Rules:
          - Conditions:
              - Field: path-pattern
                Values:
                  - '/'
            Priority: '1'
            Actions:
              - Type: forward
                TargetGroupName: "{{ operation_tg.target_group_name }}"
    state: "{{ elb_resource_state }}"
