---

- name: Create AWS RDS Instance vHost
  hosts: localhost
  connection: local
  gather_facts: True
  serial: 1
  max_fail_percentage: 0

  vars:
    vpc_name: "M100"
    region: "ap-southeast-1"
    rds_engine: "mysql5.7"
    rds_mysql_version: "mysql57"
    rds_engine_version: "5.7.22"

  roles:
    #- { role: rds.mysql-base }  #创建RDS基础环境
    - { role: rds.mysql,rds_instance_name: 'db001-m100-banna-mysql57',rds_instance_type: "db.m5.large",rds_instance_size_gb: "100",rds_ebs_iops: "1000",rds_admin_username: "dbAdmin",rds_admin_password: "opuUjcEVp0xH" }
    - { role: rds.mysql,rds_instance_name: 'db002-m100-banna-mysql57',rds_instance_type: "db.m5.large",rds_instance_size_gb: "100",rds_ebs_iops: "1000",rds_admin_username: "dbAdmin",rds_admin_password: "opuUjcEVp0xH" }
    #- { role: rds.mysql,rds_global_name: 'm100-banna-mysql57',rds_instance_name: 'db001-m100-banna-mysql57',rds_instance_type: "db.m5.large",rds_instance_size_gb: "100",rds_ebs_iops: "1000",rds_admin_username: "dbAdmin",rds_admin_password: "opuUjcEVp0xH" }

