---
# defaults file for roles/ec2
ec2_volume_type: gp2
ec2_volume_Device_Name: /dev/sda1
#ec2_region: "ap-southeast-1"
#ec2_instance_count: 1
#ec2_instance_private_Ip: "{{ ec2_subnet_ipv4_cidr }}{{ aws_tags }}"
ec2_instance_tag_name: "{{ vpc_env }}-{{ app_name }}"


#groups name varabales 
security_ng: "{{ vpc_env }}-ng-80-443-all"
security_merchant: "{{ vpc_env }}-merchant-8081"
security_agent_acl: "{{ vpc_env }}-agent-acl"
security_docker_manager: "{{ vpc_env }}-docker-manager"
security_all: "{{ vpc_env }}-all"
