---
# tasks file for roles/securitygroups
- name: provision merchant  80 all security group
  ec2_group:
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    name: "{{ vpc_env }}-merchant-80"
    description: "opens port 80 to the world"
    tags:
      "Name": "{{ vpc_env }}-merchant-80"
      "Environment": "{{ vpc_env }}-merchant-80"
    rules:
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "0.0.0.0/0"
        rule_desc: "allow all on port 80"
  register: sg_merchant_80
