---
- name: Create ElastiCache Redis instance
  hosts: localhost
  connection: local
  gather_facts: True
  serial: 1
  max_fail_percentage: 0

  vars:
    vpc_name: "M100"
    region: "ap-southeast-1"  

  roles:
    - { role: aws.es,aws_iam_id: '607624181858',domain_name: 'm100lottery',es_version: 6.8,es_instance_type: "m5.xlarge.elasticsearch",es_instance_count: "3",es_instance_volumesize: 100 } 

