---
# defaults file for roles/ec2
ec2_volume_type: gp2
ec2_volume_Device_Name: /dev/sda1
ec2_region: "ap-southeast-1"
#ec2_instance_count: 1
#ec2_instance_private_Ip: "{{ ec2_subnet_ipv4_cidr }}{{ aws_tags }}"
ec2_instance_tag_name: "{{ vpc_env }}-{{ app_name }}"


#groups name varabales 
security_elb: "{{ vpc_env }}-elb-80-443-all"
security_merchant: "{{ vpc_env }}-merchant-80"
security_zuul_all: "{{ vpc_env }}-zuul-all"
security_emqtt: "{{ vpc_env }}-emqtt"
security_nacos: "{{ vpc_env }}-nacos"
security_all: "{{ vpc_env }}-all"
security_rds: "{{ vpc_env }}-rds"
security_ssh: "{{ vpc_env }}-ssh"
security_eureka_office: "{{ vpc_env }}-eureka-office"
security_office: "{{ vpc_env }}-office-access"
security_windows: "{{ vpc_env }}-windows-ops"
security_emqtt_office: "{{ vpc_env }}-emqtt-office"
security_graylog: "{{ vpc_env }}-graylog"
security_merchant: "{{ vpc_env }}-hk-merchant"
security_backend_acl: "{{ vpc_env }}-backend-acl"


